public class MainFrame extends javax.swing.JFrame {

    static Vertex source = null;
    static Vertex destination = null;
    static final int vertexNum = 13;
    static Vertex [] vertices = new Vertex[vertexNum];
    static FindPathDFS obj = new FindPathDFS();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Header = new javax.swing.JLabel();
        Origin = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Destination = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Path = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Header.setText("Welcome to USM Main Campus");

        Origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masjid", "CS School", "Fajar", "Eureka", "DTSP", "Library", "Padang Kawad", "Sg. Dua Gate", "Subaidah", "Bukit Gambir Gate", "Swimming Pool", "RST", "Minden Gate" }));
        Origin.setMinimumSize(new java.awt.Dimension(90, 22));
        Origin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriginActionPerformed(evt);
            }
        });

        jLabel1.setText("Origin");

        Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masjid", "CS School", "Fajar", "Eureka", "DTSP", "Library", "Padang Kawad", "Sg. Dua Gate", "Subaidah", "Bukit Gambir Gate", "Swimming Pool", "RST", "Minden Gate" }));
        Destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationActionPerformed(evt);
            }
        });

        jLabel3.setText("Destination");

        SearchButton.setText("Search route");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        Path.setText("Path");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(Path)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Path)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Origin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(SearchButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(Header))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Header)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>                        

    private void OriginActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
    }                                      

    private void DestinationActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
    }                                           

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {     

        for (int i=0; i<vertexNum; i++){
            if (vertices[i].getName().equals(Origin.getSelectedItem().toString())){
                source = vertices[i];
            } 
            if (vertices[i].getName().equals(Destination.getSelectedItem().toString()))
            {
                destination = vertices[i];
            }     
        }                                        
        obj.FindPath(source, destination);
        Path.setText(obj.path);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });

        String [] locations = {"Masjid", "CS School","Fajar","Eureka","DTSP","Library","Padang Kawad","Sg. Dua Gate","Subaidah","Bukit Gambir Gate","Swimming Pool","RST","Minden Gate"};
        for (int i=0; i<vertexNum; i++)
        {
            vertices[i] = new Vertex(i,locations[i]);
        }

        vertices[0].addNeighbour(vertices[1]);
        vertices[0].addNeighbour(vertices[2]);
        vertices[0].addNeighbour(vertices[3]);
        vertices[0].addNeighbour(vertices[4]);
        vertices[0].addNeighbour(vertices[5]);

        vertices[1].addNeighbour(vertices[0]);
        vertices[1].addNeighbour(vertices[6]);

        vertices[2].addNeighbour(vertices[0]);
        vertices[2].addNeighbour(vertices[6]);

        vertices[3].addNeighbour(vertices[0]);
        vertices[3].addNeighbour(vertices[7]);

        vertices[4].addNeighbour(vertices[0]);
        vertices[4].addNeighbour(vertices[8]);

        vertices[5].addNeighbour(vertices[0]);

        vertices[6].addNeighbour(vertices[1]);
        vertices[6].addNeighbour(vertices[2]);
        vertices[6].addNeighbour(vertices[9]);

        vertices[7].addNeighbour(vertices[3]);

        vertices[8].addNeighbour(vertices[4]);
        vertices[8].addNeighbour(vertices[10]);

        vertices[9].addNeighbour(vertices[6]);
        vertices[9].addNeighbour(vertices[11]);

        vertices[10].addNeighbour(vertices[8]);
        vertices[10].addNeighbour(vertices[12]);

        vertices[11].addNeighbour(vertices[9]);

        vertices[12].addNeighbour(vertices[10]);

    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> Destination;
    private javax.swing.JLabel Header;
    private javax.swing.JComboBox<String> Origin;
    private javax.swing.JLabel Path;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
